import { defineConfig, externalizeDepsPlugin } from 'electron-vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import { resolve } from 'path'

export default defineConfig({
  main: {
    plugins: [externalizeDepsPlugin()],
    build: {
      outDir: 'out/main',
      rollupOptions: {
        input: {
          index: resolve(__dirname, 'src/main/index.ts')
        }
      }
    }
  },
  preload: {
    // The sandboxed renderer requires the CJS preload generated by
    // scripts/build-preload.mjs; keep electron-vite's ESM output separate.
    plugins: [externalizeDepsPlugin()],
    build: {
      outDir: 'out/preload-unused'
    }
  },
  renderer: {
    root: 'src/renderer',
    plugins: [react(), tailwindcss()],
    resolve: { alias: { '@': resolve(__dirname, 'src/renderer') } },
    build: {
      outDir: '../../out/renderer'
    }
  }
})
